name: "bike4mind OpenAI Shim"
description: "OpenAI-compatible API shim for bike4mind integration with Home Assistant"
version: "1.1.1"
slug: "b4m_shim"
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  3000/tcp: 3000
options:
  b4m_api_key: ""
  ha_b4m_session_id: ""
  b4m_user_id: ""
  shim_api_key: ""
  b4m_model: "gpt-4o-mini"
  session_ttl_sec: 600
  max_turns: 20
  timeout_ms: 60000
  poll_interval_ms: 1500
  poll_max_interval_ms: 5000
  b4m_base: "https://app.bike4mind.com/api"
  ha_tool_function_name: "homeassistant.call_service"
schema:
  b4m_api_key: str
  ha_b4m_session_id: str
  b4m_user_id: str
  shim_api_key: str?
  b4m_model: str?
  session_ttl_sec: int(1,3600)?
  max_turns: int(1,100)?
  timeout_ms: int(5000,120000)?
  poll_interval_ms: int(500,10000)?
  poll_max_interval_ms: int(1000,30000)?
  b4m_base: url?
  ha_tool_function_name: str?
